BOOKLY_DATA = {
    "as_of_date": "2026-08-22",
    "policies": {
        "standard_return_days": 30,
        "autonomous_refund_limit": 50.0,
        "human_approval_limit": 250.0,
        "collector_edition_requires_review": True,
        "replacement_limit": 1,
        "password_reset_requires_identity_verification": True,
        "payment_methods": ["Visa ending 4242", "PayPal", "Bookly Credit"],
        "shipping_methods": ["Economy Parcel", "Standard Tracked", "Express Air"]
    },
    "books": {
        "BK1001": {
            "book_id": "BK1001",
            "title": "The Hobbit",
            "author": "J. R. R. Tolkien",
            "genre": "fantasy",
            "format": "paperback",
            "price": 25.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1002": {
            "book_id": "BK1002",
            "title": "Rare First Edition",
            "author": "Eleanor Voss",
            "genre": "literary fiction",
            "format": "collector hardcover",
            "price": 250.0,
            "stock_status": "limited_stock",
            "is_collector_edition": True,
            "return_eligible": True
        },
        "BK1003": {
            "book_id": "BK1003",
            "title": "The Sea Glass Atlas",
            "author": "Mara Bell",
            "genre": "travel",
            "format": "hardcover",
            "price": 32.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1004": {
            "book_id": "BK1004",
            "title": "The Cartographer's Lantern",
            "author": "Jonas Reed",
            "genre": "mystery",
            "format": "paperback",
            "price": 48.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1005": {
            "book_id": "BK1005",
            "title": "Quiet Machines",
            "author": "Nia Okafor",
            "genre": "science fiction",
            "format": "ebook",
            "price": 18.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": False
        },
        "BK1006": {
            "book_id": "BK1006",
            "title": "The Last Orchard",
            "author": "Celia Hart",
            "genre": "historical fiction",
            "format": "hardcover",
            "price": 64.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1007": {
            "book_id": "BK1007",
            "title": "Winter at Platform Nine",
            "author": "Theo March",
            "genre": "romance",
            "format": "paperback",
            "price": 22.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1008": {
            "book_id": "BK1008",
            "title": "Orbits of Home",
            "author": "Priyanka Sen",
            "genre": "essays",
            "format": "hardcover",
            "price": 75.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1009": {
            "book_id": "BK1009",
            "title": "A Pocket Guide to Moon Gardens",
            "author": "Iris Vale",
            "genre": "gardening",
            "format": "paperback",
            "price": 14.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1010": {
            "book_id": "BK1010",
            "title": "Salt & Signal",
            "author": "Ari Calder",
            "genre": "thriller",
            "format": "audiobook",
            "price": 41.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": False
        },
        "BK1011": {
            "book_id": "BK1011",
            "title": "The Glass Hotelier",
            "author": "Beatrice Wynn",
            "genre": "literary fiction",
            "format": "paperback",
            "price": 29.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1012": {
            "book_id": "BK1012",
            "title": "Mango Season in Reverse",
            "author": "Lina Perera",
            "genre": "family saga",
            "format": "hardcover",
            "price": 36.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1013": {
            "book_id": "BK1013",
            "title": "The Quiet Harbor",
            "author": "Wren Osei",
            "genre": "literary fiction",
            "format": "paperback",
            "price": 50.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        },
        "BK1014": {
            "book_id": "BK1014",
            "title": "Midnight Ledger",
            "author": "Wren Osei",
            "genre": "thriller",
            "format": "paperback",
            "price": 51.0,
            "stock_status": "in_stock",
            "is_collector_edition": False,
            "return_eligible": True
        }
    },
    "customers": {
        "C1001": {
            "customer_id": "C1001",
            "first_name": "Sarah",
            "last_name": "Marlow",
            "email": "sarah.marlow@example.com",
            "country": "United States",
            "account_created": "2024-03-18",
            "loyalty_tier": "silver",
            "total_orders": 2,
            "previous_refunds": 0,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 3,
            "preferred_currency": "AUD"
        },
        "C1002": {
            "customer_id": "C1002",
            "first_name": "Michael",
            "last_name": "Rowan",
            "email": "michael.rowan@example.com",
            "country": "Canada",
            "account_created": "2022-11-02",
            "loyalty_tier": "gold",
            "total_orders": 3,
            "previous_refunds": 4,
            "previous_missing_delivery_claims": 4,
            "recent_support_cases": 4,
            "preferred_currency": "AUD"
        },
        "C1003": {
            "customer_id": "C1003",
            "first_name": "Aisha",
            "last_name": "Ndlovu",
            "email": "aisha.ndlovu@example.com",
            "country": "South Africa",
            "account_created": "2025-01-26",
            "loyalty_tier": "bronze",
            "total_orders": 2,
            "previous_refunds": 1,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 2,
            "preferred_currency": "AUD"
        },
        "C1004": {
            "customer_id": "C1004",
            "first_name": "Liam",
            "last_name": "Chen",
            "email": "liam.chen@example.com",
            "country": "Singapore",
            "account_created": "2026-02-11",
            "loyalty_tier": "bronze",
            "total_orders": 1,
            "previous_refunds": 0,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 2,
            "preferred_currency": "AUD"
        },
        "C1005": {
            "customer_id": "C1005",
            "first_name": "Priya",
            "last_name": "Desai",
            "email": "priya.desai@example.com",
            "country": "United Kingdom",
            "account_created": "2023-07-09",
            "loyalty_tier": "gold",
            "total_orders": 2,
            "previous_refunds": 1,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 3,
            "preferred_currency": "AUD"
        },
        "C1006": {
            "customer_id": "C1006",
            "first_name": "Noah",
            "last_name": "Bennett",
            "email": "noah.bennett@example.com",
            "country": "United States",
            "account_created": "2021-09-14",
            "loyalty_tier": "platinum",
            "total_orders": 2,
            "previous_refunds": 2,
            "previous_missing_delivery_claims": 2,
            "recent_support_cases": 4,
            "preferred_currency": "AUD"
        },
        "C1007": {
            "customer_id": "C1007",
            "first_name": "Emma",
            "last_name": "Kovacs",
            "email": "emma.kovacs@example.com",
            "country": "Germany",
            "account_created": "2024-12-01",
            "loyalty_tier": "silver",
            "total_orders": 2,
            "previous_refunds": 0,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 2,
            "preferred_currency": "AUD"
        },
        "C1008": {
            "customer_id": "C1008",
            "first_name": "Hugo",
            "last_name": "Martins",
            "email": "hugo.martins@example.com",
            "country": "Portugal",
            "account_created": "2025-05-22",
            "loyalty_tier": "silver",
            "total_orders": 3,
            "previous_refunds": 1,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 4,
            "preferred_currency": "AUD"
        },
        "C1009": {
            "customer_id": "C1009",
            "first_name": "Sofia",
            "last_name": "Ibarra",
            "email": "sofia.ibarra@example.com",
            "country": "Mexico",
            "account_created": "2023-10-17",
            "loyalty_tier": "gold",
            "total_orders": 2,
            "previous_refunds": 1,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 3,
            "preferred_currency": "AUD"
        },
        "C1010": {
            "customer_id": "C1010",
            "first_name": "Daniel",
            "last_name": "Okoro",
            "email": "daniel.okoro@example.com",
            "country": "Nigeria",
            "account_created": "2026-04-05",
            "loyalty_tier": "bronze",
            "total_orders": 1,
            "previous_refunds": 0,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 3,
            "preferred_currency": "AUD"
        },
        "C1011": {
            "customer_id": "C1011",
            "first_name": "Grace",
            "last_name": "Whitfield",
            "email": "grace.whitfield@example.com",
            "country": "United States",
            "account_created": "2025-09-02",
            "loyalty_tier": "silver",
            "total_orders": 1,
            "previous_refunds": 0,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 1,
            "preferred_currency": "AUD"
        },
        "C1012": {
            "customer_id": "C1012",
            "first_name": "Owen",
            "last_name": "Castillo",
            "email": "owen.castillo@example.com",
            "country": "United States",
            "account_created": "2025-11-14",
            "loyalty_tier": "silver",
            "total_orders": 1,
            "previous_refunds": 0,
            "previous_missing_delivery_claims": 0,
            "recent_support_cases": 1,
            "preferred_currency": "AUD"
        }
    },
    "orders": {
        "B1001": {
            "order_id": "B1001",
            "customer_id": "C1001",
            "book_id": "BK1001",
            "order_date": "2026-08-18",
            "quantity": 1,
            "unit_price": 25.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delayed",
            "shipping_method": "Economy Parcel",
            "expected_delivery": "2026-08-26",
            "delivered_date": None,
            "tracking_status": "carrier_delay",
            "tracking_last_updated": "2026-08-21",
            "shipping_address_country": "United States",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-17",
            "issue_tags": ["delayed", "carrier_delay"],
            "express_replacement_available": True,
            "express_replacement_eta": "2026-08-23",
            "express_replacement_cost_to_bookly": "low"
        },
        "B1002": {
            "order_id": "B1002",
            "customer_id": "C1002",
            "book_id": "BK1002",
            "order_date": "2026-08-12",
            "quantity": 1,
            "unit_price": 250.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delayed",
            "shipping_method": "Express Air",
            "expected_delivery": "2026-08-20",
            "delivered_date": None,
            "tracking_status": "carrier_delay",
            "tracking_last_updated": "2026-08-21",
            "shipping_address_country": "Canada",
            "previous_refund_count": 4,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-18",
            "issue_tags": ["collector_edition", "delayed"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1003": {
            "order_id": "B1003",
            "customer_id": "C1003",
            "book_id": "BK1003",
            "order_date": "2026-08-17",
            "quantity": 1,
            "unit_price": 32.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "shipped",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-27",
            "delivered_date": None,
            "tracking_status": "in_transit",
            "tracking_last_updated": "2026-08-21",
            "shipping_address_country": "South Africa",
            "previous_refund_count": 1,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-16",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1004": {
            "order_id": "B1004",
            "customer_id": "C1003",
            "book_id": "BK1004",
            "order_date": "2026-08-05",
            "quantity": 1,
            "unit_price": 48.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delivered",
            "shipping_method": "Express Air",
            "expected_delivery": "2026-08-15",
            "delivered_date": "2026-08-14",
            "tracking_status": "delivered",
            "tracking_last_updated": "2026-08-14",
            "shipping_address_country": "South Africa",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-13",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1005": {
            "order_id": "B1005",
            "customer_id": "C1004",
            "book_id": "BK1005",
            "order_date": "2026-08-20",
            "quantity": 1,
            "unit_price": 18.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "processing",
            "shipping_method": "Economy Parcel",
            "expected_delivery": "2026-08-29",
            "delivered_date": None,
            "tracking_status": "label_created",
            "tracking_last_updated": "2026-08-20",
            "shipping_address_country": "Singapore",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-19",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1006": {
            "order_id": "B1006",
            "customer_id": "C1005",
            "book_id": "BK1006",
            "order_date": "2026-07-10",
            "quantity": 1,
            "unit_price": 64.0,
            "currency": "AUD",
            "payment_status": "refunded",
            "fulfillment_status": "returned",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-07-16",
            "delivered_date": "2026-07-14",
            "tracking_status": "returned_to_sender",
            "tracking_last_updated": "2026-08-04",
            "shipping_address_country": "United Kingdom",
            "previous_refund_count": 1,
            "refund_amount": 64.0,
            "return_window_ends": "2026-08-13",
            "issue_tags": ["return_requested", "returned"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1007": {
            "order_id": "B1007",
            "customer_id": "C1006",
            "book_id": "BK1007",
            "order_date": "2026-07-26",
            "quantity": 1,
            "unit_price": 22.0,
            "currency": "AUD",
            "payment_status": "refunded",
            "fulfillment_status": "lost",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-01",
            "delivered_date": None,
            "tracking_status": "tracking_stopped",
            "tracking_last_updated": "2026-08-06",
            "shipping_address_country": "United States",
            "previous_refund_count": 2,
            "refund_amount": 22.0,
            "return_window_ends": "2026-08-25",
            "issue_tags": ["missing_delivery", "lost_shipment"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1008": {
            "order_id": "B1008",
            "customer_id": "C1007",
            "book_id": "BK1008",
            "order_date": "2026-08-01",
            "quantity": 1,
            "unit_price": 75.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delivered",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-10",
            "delivered_date": "2026-08-09",
            "tracking_status": "delivered",
            "tracking_last_updated": "2026-08-09",
            "shipping_address_country": "Germany",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-08",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1009": {
            "order_id": "B1009",
            "customer_id": "C1008",
            "book_id": "BK1009",
            "order_date": "2026-08-05",
            "quantity": 1,
            "unit_price": 14.0,
            "currency": "AUD",
            "payment_status": "cancelled",
            "fulfillment_status": "cancelled",
            "shipping_method": "Economy Parcel",
            "expected_delivery": "2026-08-12",
            "delivered_date": None,
            "tracking_status": "label_created",
            "tracking_last_updated": "2026-08-05",
            "shipping_address_country": "Portugal",
            "previous_refund_count": 1,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-04",
            "issue_tags": ["cancelled"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1010": {
            "order_id": "B1010",
            "customer_id": "C1008",
            "book_id": "BK1010",
            "order_date": "2026-08-20",
            "quantity": 1,
            "unit_price": 41.0,
            "currency": "AUD",
            "payment_status": "payment_pending",
            "fulfillment_status": "payment_pending",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-29",
            "delivered_date": None,
            "tracking_status": "label_created",
            "tracking_last_updated": "2026-08-20",
            "shipping_address_country": "Portugal",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-19",
            "issue_tags": ["payment_pending"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1011": {
            "order_id": "B1011",
            "customer_id": "C1008",
            "book_id": "BK1011",
            "order_date": "2026-08-11",
            "quantity": 1,
            "unit_price": 29.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "shipped",
            "shipping_method": "Express Air",
            "expected_delivery": "2026-08-22",
            "delivered_date": None,
            "tracking_status": "out_for_delivery",
            "tracking_last_updated": "2026-08-22",
            "shipping_address_country": "Portugal",
            "previous_refund_count": 1,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-21",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1012": {
            "order_id": "B1012",
            "customer_id": "C1009",
            "book_id": "BK1012",
            "order_date": "2026-08-08",
            "quantity": 1,
            "unit_price": 36.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delivered",
            "shipping_method": "Express Air",
            "expected_delivery": "2026-08-20",
            "delivered_date": "2026-08-20",
            "tracking_status": "delivered",
            "tracking_last_updated": "2026-08-20",
            "shipping_address_country": "Mexico",
            "previous_refund_count": 1,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-19",
            "issue_tags": ["international"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1013": {
            "order_id": "B1013",
            "customer_id": "C1009",
            "book_id": "BK1003",
            "order_date": "2026-06-01",
            "quantity": 1,
            "unit_price": 32.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "returned",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-06-08",
            "delivered_date": "2026-06-05",
            "tracking_status": "returned_to_sender",
            "tracking_last_updated": "2026-07-20",
            "shipping_address_country": "Mexico",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-07-05",
            "issue_tags": ["return_requested", "return_window_expired"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1014": {
            "order_id": "B1014",
            "customer_id": "C1010",
            "book_id": "BK1004",
            "order_date": "2026-08-02",
            "quantity": 1,
            "unit_price": 48.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "preorder",
            "shipping_method": "Express Air",
            "expected_delivery": "2026-09-15",
            "delivered_date": None,
            "tracking_status": "label_created",
            "tracking_last_updated": "2026-08-02",
            "shipping_address_country": "Nigeria",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-10-15",
            "issue_tags": ["preorder"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1015": {
            "order_id": "B1015",
            "customer_id": "C1001",
            "book_id": "BK1011",
            "order_date": "2026-08-06",
            "quantity": 1,
            "unit_price": 29.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delivered",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-16",
            "delivered_date": "2026-08-15",
            "tracking_status": "delivered",
            "tracking_last_updated": "2026-08-15",
            "shipping_address_country": "United States",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-14",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1016": {
            "order_id": "B1016",
            "customer_id": "C1002",
            "book_id": "BK1008",
            "order_date": "2026-07-18",
            "quantity": 1,
            "unit_price": 75.0,
            "currency": "AUD",
            "payment_status": "refunded",
            "fulfillment_status": "returned",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-07-25",
            "delivered_date": "2026-07-23",
            "tracking_status": "returned_to_sender",
            "tracking_last_updated": "2026-08-12",
            "shipping_address_country": "Canada",
            "previous_refund_count": 4,
            "refund_amount": 75.0,
            "return_window_ends": "2026-08-22",
            "issue_tags": ["return_requested", "returned"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1017": {
            "order_id": "B1017",
            "customer_id": "C1002",
            "book_id": "BK1005",
            "order_date": "2026-08-21",
            "quantity": 1,
            "unit_price": 18.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "processing",
            "shipping_method": "Economy Parcel",
            "expected_delivery": "2026-08-31",
            "delivered_date": None,
            "tracking_status": "label_created",
            "tracking_last_updated": "2026-08-21",
            "shipping_address_country": "Canada",
            "previous_refund_count": 4,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-20",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1018": {
            "order_id": "B1018",
            "customer_id": "C1005",
            "book_id": "BK1009",
            "order_date": "2026-07-23",
            "quantity": 1,
            "unit_price": 14.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delivered",
            "shipping_method": "Economy Parcel",
            "expected_delivery": "2026-07-30",
            "delivered_date": "2026-07-28",
            "tracking_status": "delivered",
            "tracking_last_updated": "2026-07-28",
            "shipping_address_country": "United Kingdom",
            "previous_refund_count": 1,
            "refund_amount": 0.0,
            "return_window_ends": "2026-08-27",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1019": {
            "order_id": "B1019",
            "customer_id": "C1006",
            "book_id": "BK1001",
            "order_date": "2026-08-04",
            "quantity": 2,
            "unit_price": 25.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "delivered",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-14",
            "delivered_date": "2026-08-15",
            "tracking_status": "delivered",
            "tracking_last_updated": "2026-08-15",
            "shipping_address_country": "United States",
            "previous_refund_count": 2,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-14",
            "issue_tags": ["late_delivery"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1020": {
            "order_id": "B1020",
            "customer_id": "C1007",
            "book_id": "BK1012",
            "order_date": "2026-08-18",
            "quantity": 1,
            "unit_price": 36.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "shipped",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-25",
            "delivered_date": None,
            "tracking_status": "in_transit",
            "tracking_last_updated": "2026-08-21",
            "shipping_address_country": "Germany",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-17",
            "issue_tags": [],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1021": {
            "order_id": "B1021",
            "customer_id": "C1011",
            "book_id": "BK1013",
            "order_date": "2026-08-05",
            "quantity": 1,
            "unit_price": 50.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "lost",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-12",
            "delivered_date": None,
            "tracking_status": "tracking_stopped",
            "tracking_last_updated": "2026-08-13",
            "shipping_address_country": "United States",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-11",
            "issue_tags": ["missing_delivery", "lost_shipment"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        },
        "B1022": {
            "order_id": "B1022",
            "customer_id": "C1012",
            "book_id": "BK1014",
            "order_date": "2026-08-06",
            "quantity": 1,
            "unit_price": 51.0,
            "currency": "AUD",
            "payment_status": "paid",
            "fulfillment_status": "lost",
            "shipping_method": "Standard Tracked",
            "expected_delivery": "2026-08-13",
            "delivered_date": None,
            "tracking_status": "tracking_stopped",
            "tracking_last_updated": "2026-08-14",
            "shipping_address_country": "United States",
            "previous_refund_count": 0,
            "refund_amount": 0.0,
            "return_window_ends": "2026-09-12",
            "issue_tags": ["missing_delivery", "lost_shipment"],
            "express_replacement_available": False,
            "express_replacement_eta": None,
            "express_replacement_cost_to_bookly": None
        }
    },
    "support_history": {
        "C2001": {
            "case_id": "C2001",
            "customer_id": "C1001",
            "order_id": "B1001",
            "created_at": "2026-08-21T09:14:00",
            "issue_type": "delivery_delay",
            "customer_message_summary": "The Hobbit has not moved since the carrier scan and the delivery date is approaching.",
            "resolution": "Confirmed a carrier delay and advised that the parcel is still in the delivery network.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Low-value order is within the autonomous refund threshold if the delay becomes a confirmed loss."
        },
        "C2002": {
            "case_id": "C2002",
            "customer_id": "C1001",
            "order_id": "B1001",
            "created_at": "2026-08-22T08:40:00",
            "issue_type": "refund_request",
            "customer_message_summary": "Sarah asked for a refund because the delayed parcel will miss a planned trip.",
            "resolution": "Refund request placed on hold pending the carrier delay review and updated delivery estimate.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Requested refund is 25.00 AUD and has no prior refund history."
        },
        "C2003": {
            "case_id": "C2003",
            "customer_id": "C1001",
            "order_id": "B1015",
            "created_at": "2026-08-16T11:05:00",
            "issue_type": "delivery_confirmation",
            "customer_message_summary": "Sarah confirmed that her second book arrived in good condition.",
            "resolution": "No action required; delivery was confirmed as complete.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Normal delivered order with no issue."
        },
        "C2004": {
            "case_id": "C2004",
            "customer_id": "C1002",
            "order_id": "B1002",
            "created_at": "2026-08-20T10:12:00",
            "issue_type": "refund_request",
            "customer_message_summary": "Michael says the delivered Rare First Edition is not what he expected and wants a full refund.",
            "resolution": "Explained that a collector-edition refund requires human review and requested condition photographs.",
            "refund_issued": False,
            "escalated": True,
            "notes": "250.00 AUD collector edition; automatic refund prohibited by policy. Customer has four previous refunds."
        },
        "C2005": {
            "case_id": "C2005",
            "customer_id": "C1002",
            "order_id": "B1016",
            "created_at": "2026-08-12T14:22:00",
            "issue_type": "return_request",
            "customer_message_summary": "Michael returned a regular hardcover after deciding it was not suitable for his collection.",
            "resolution": "Return received and 75.00 AUD was refunded to the original payment method.",
            "refund_issued": True,
            "escalated": False,
            "notes": "Return was initiated before the return window ended."
        },
        "C2006": {
            "case_id": "C2006",
            "customer_id": "C1002",
            "order_id": None,
            "created_at": "2026-08-14T07:48:00",
            "issue_type": "password_reset",
            "customer_message_summary": "Michael cannot access his account and asked support to reset the password.",
            "resolution": "Identity verification was requested before any password-reset link could be issued.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Password reset requires identity verification under the account-security policy."
        },
        "C2007": {
            "case_id": "C2007",
            "customer_id": "C1002",
            "order_id": "B1017",
            "created_at": "2026-08-22T09:01:00",
            "issue_type": "payment_pending",
            "customer_message_summary": "Michael sees a pending payment and wants to know whether the ebook order is confirmed.",
            "resolution": "Explained that fulfillment will begin after payment authorization completes.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Order remains payment_pending; no delivery commitment has been made."
        },
        "C2008": {
            "case_id": "C2008",
            "customer_id": "C1003",
            "order_id": "B1003",
            "created_at": "2026-08-21T16:30:00",
            "issue_type": "tracking_question",
            "customer_message_summary": "Aisha asked whether the parcel has left the regional sorting center.",
            "resolution": "Provided the latest in-transit scan and the expected delivery date.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No carrier exception is present."
        },
        "C2009": {
            "case_id": "C2009",
            "customer_id": "C1003",
            "order_id": "B1004",
            "created_at": "2026-08-15T09:44:00",
            "issue_type": "delivery_confirmation",
            "customer_message_summary": "Aisha reported that the mystery paperback arrived safely.",
            "resolution": "Thanked the customer and closed the case.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Delivered without damage or delay."
        },
        "C2010": {
            "case_id": "C2010",
            "customer_id": "C1004",
            "order_id": None,
            "created_at": "2026-08-20T12:18:00",
            "issue_type": "missing_order_number",
            "customer_message_summary": "Liam says a book was ordered but cannot find the order number in his email.",
            "resolution": "Asked Liam to confirm the account email, approximate purchase date, and delivery country before locating an order.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Order clarification is required; no order was assumed from incomplete information."
        },
        "C2011": {
            "case_id": "C2011",
            "customer_id": "C1004",
            "order_id": "B1005",
            "created_at": "2026-08-21T13:37:00",
            "issue_type": "order_status",
            "customer_message_summary": "Liam asked why his digital title still shows as processing.",
            "resolution": "Explained that the order is being prepared and that the access email will follow payment confirmation.",
            "refund_issued": False,
            "escalated": False,
            "notes": "The order is not yet late relative to its expected delivery date."
        },
        "C2012": {
            "case_id": "C2012",
            "customer_id": "C1005",
            "order_id": "B1006",
            "created_at": "2026-08-03T10:20:00",
            "issue_type": "return_request",
            "customer_message_summary": "Priya wants to return the hardcover within the stated return period.",
            "resolution": "Return label issued and return instructions provided.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Return request is within 30 days of delivery."
        },
        "C2013": {
            "case_id": "C2013",
            "customer_id": "C1005",
            "order_id": "B1006",
            "created_at": "2026-08-04T15:48:00",
            "issue_type": "return_received",
            "customer_message_summary": "Priya confirmed that the returned book was handed to the carrier.",
            "resolution": "Return was accepted and a 64.00 AUD refund was issued.",
            "refund_issued": True,
            "escalated": False,
            "notes": "Refund equals one returned unit and does not exceed the order value."
        },
        "C2014": {
            "case_id": "C2014",
            "customer_id": "C1005",
            "order_id": "B1018",
            "created_at": "2026-07-29T08:03:00",
            "issue_type": "book_condition",
            "customer_message_summary": "Priya asked whether a small crease on the paperback cover was normal.",
            "resolution": "Provided a condition guide and offered a replacement if the defect worsens.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No replacement requested."
        },
        "C2015": {
            "case_id": "C2015",
            "customer_id": "C1006",
            "order_id": "B1007",
            "created_at": "2026-08-03T17:11:00",
            "issue_type": "missing_delivery",
            "customer_message_summary": "Noah says the paperback was not delivered even though the expected date has passed.",
            "resolution": "Opened a carrier trace and asked Noah to confirm the delivery address and check nearby safe locations.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Tracking has not advanced since the 2026-08-06 carrier handoff."
        },
        "C2016": {
            "case_id": "C2016",
            "customer_id": "C1006",
            "order_id": "B1007",
            "created_at": "2026-08-10T11:26:00",
            "issue_type": "lost_shipment_claim",
            "customer_message_summary": "Noah provided a plausible missing-shipment claim after the carrier trace found no new scan.",
            "resolution": "Confirmed the parcel lost and issued a 22.00 AUD refund.",
            "refund_issued": True,
            "escalated": False,
            "notes": "Low-value lost shipment; refund was within the autonomous limit."
        },
        "C2017": {
            "case_id": "C2017",
            "customer_id": "C1006",
            "order_id": "B1019",
            "created_at": "2026-08-16T10:02:00",
            "issue_type": "late_delivery",
            "customer_message_summary": "Noah reported that the two-copy order arrived one day after the estimate.",
            "resolution": "Apologized for the one-day carrier delay; no refund was warranted after successful delivery.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Customer has prior missing-delivery claims, so the delivery scan was verified carefully."
        },
        "C2018": {
            "case_id": "C2018",
            "customer_id": "C1006",
            "order_id": None,
            "created_at": "2026-08-18T18:19:00",
            "issue_type": "address_update",
            "customer_message_summary": "Noah asked how to change his saved delivery address for future orders.",
            "resolution": "Directed him to account settings and confirmed no open order was affected.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No order-level action needed."
        },
        "C2019": {
            "case_id": "C2019",
            "customer_id": "C1007",
            "order_id": "B1008",
            "created_at": "2026-08-10T09:32:00",
            "issue_type": "delivery_confirmation",
            "customer_message_summary": "Emma asked whether the delivered essay collection was left with a neighbor.",
            "resolution": "Confirmed the carrier delivery scan and neighbor delivery note.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Normal delivered order with no issue."
        },
        "C2020": {
            "case_id": "C2020",
            "customer_id": "C1007",
            "order_id": "B1020",
            "created_at": "2026-08-21T15:05:00",
            "issue_type": "dispatch_question",
            "customer_message_summary": "Emma asked when the family saga would leave the sorting center.",
            "resolution": "Shared the in-transit scan and confirmed delivery is still expected on 2026-08-25.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No delay or delivery exception is currently recorded."
        },
        "C2021": {
            "case_id": "C2021",
            "customer_id": "C1008",
            "order_id": "B1009",
            "created_at": "2026-08-05T08:55:00",
            "issue_type": "cancellation_request",
            "customer_message_summary": "Hugo asked to cancel the gardening guide before dispatch.",
            "resolution": "Order cancellation was completed before shipment and no delivery was recorded.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Cancellation is reflected in the order status."
        },
        "C2022": {
            "case_id": "C2022",
            "customer_id": "C1008",
            "order_id": "B1010",
            "created_at": "2026-08-20T19:43:00",
            "issue_type": "payment_pending",
            "customer_message_summary": "Hugo received a payment-pending notice for the audiobook.",
            "resolution": "Explained that the payment provider has not yet authorized the charge.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No fulfillment action is taken until payment clears."
        },
        "C2023": {
            "case_id": "C2023",
            "customer_id": "C1008",
            "order_id": "B1011",
            "created_at": "2026-08-22T07:26:00",
            "issue_type": "delivery_estimate",
            "customer_message_summary": "Hugo asked if the paperback would arrive today after it changed to out for delivery.",
            "resolution": "Confirmed the out-for-delivery status and advised that the carrier estimate remains today.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Tracking was last updated on the current date."
        },
        "C2024": {
            "case_id": "C2024",
            "customer_id": "C1008",
            "order_id": None,
            "created_at": "2026-08-09T12:04:00",
            "issue_type": "password_reset",
            "customer_message_summary": "Hugo asked support to reset his password from a new device.",
            "resolution": "Sent the standard identity-verification instructions; reset remains pending verification.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No password reset is performed without identity verification."
        },
        "C2025": {
            "case_id": "C2025",
            "customer_id": "C1009",
            "order_id": "B1012",
            "created_at": "2026-08-21T10:40:00",
            "issue_type": "international_delivery",
            "customer_message_summary": "Sofia asked whether import charges were included in the express international delivery price.",
            "resolution": "Explained that local duties may be assessed separately by the destination country.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Order was delivered to Mexico on the expected date."
        },
        "C2026": {
            "case_id": "C2026",
            "customer_id": "C1009",
            "order_id": "B1013",
            "created_at": "2026-07-20T09:15:00",
            "issue_type": "return_request",
            "customer_message_summary": "Sofia requested a return more than 30 days after the book was delivered.",
            "resolution": "Return was declined because the standard return window ended on 2026-07-05.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Return-window exception was not approved."
        },
        "C2027": {
            "case_id": "C2027",
            "customer_id": "C1009",
            "order_id": "B1013",
            "created_at": "2026-07-21T14:50:00",
            "issue_type": "return_appeal",
            "customer_message_summary": "Sofia appealed the expired return decision, citing a delayed move between homes.",
            "resolution": "Maintained the original decision and provided the policy link and appeal rationale.",
            "refund_issued": False,
            "escalated": True,
            "notes": "No product defect was documented."
        },
        "C2028": {
            "case_id": "C2028",
            "customer_id": "C1010",
            "order_id": "B1014",
            "created_at": "2026-08-03T13:17:00",
            "issue_type": "preorder_timing",
            "customer_message_summary": "Daniel asked when the preorder would ship to Nigeria.",
            "resolution": "Confirmed the provisional 2026-09-15 delivery estimate and explained that dispatch follows publication release.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Preorder is not late as of the fixed dataset date."
        },
        "C2029": {
            "case_id": "C2029",
            "customer_id": "C1010",
            "order_id": None,
            "created_at": "2026-08-07T06:25:00",
            "issue_type": "password_reset",
            "customer_message_summary": "Daniel reported that he forgot his password and could not sign in from Lagos.",
            "resolution": "Requested identity verification and advised Daniel not to share the current password with support.",
            "refund_issued": False,
            "escalated": False,
            "notes": "Account recovery cannot proceed until identity verification is complete."
        },
        "C2030": {
            "case_id": "C2030",
            "customer_id": "C1010",
            "order_id": "B1014",
            "created_at": "2026-08-19T11:41:00",
            "issue_type": "preorder_update",
            "customer_message_summary": "Daniel asked whether his preferred email address can be updated before preorder release.",
            "resolution": "Directed him to profile settings and confirmed that the preorder remains attached to the account.",
            "refund_issued": False,
            "escalated": False,
            "notes": "No change to order fulfillment was required."
        },
        "C2031": {
            "case_id": "C2031",
            "customer_id": "C1011",
            "order_id": "B1021",
            "created_at": "2026-08-13T09:20:00",
            "issue_type": "refund_request",
            "customer_message_summary": "Grace says her paperback never arrived and tracking has stopped updating.",
            "resolution": "Confirmed the parcel lost and issued a 50.00 AUD refund.",
            "refund_issued": True,
            "escalated": False,
            "notes": "Requested refund is exactly at the 50.00 AUD autonomous refund limit; customer has no prior claims."
        },
        "C2032": {
            "case_id": "C2032",
            "customer_id": "C1012",
            "order_id": "B1022",
            "created_at": "2026-08-14T09:20:00",
            "issue_type": "refund_request",
            "customer_message_summary": "Owen says his paperback never arrived and tracking has stopped updating.",
            "resolution": "Refund request placed on hold pending human review because it exceeds the autonomous refund limit.",
            "refund_issued": False,
            "escalated": True,
            "notes": "Requested refund is 51.00 AUD, one dollar above the 50.00 AUD autonomous refund limit; customer has no prior claims."
        }
    }
}
